### PR TITLE
Add functions to set source/sink volumes

### PR DESCRIPTION
**Pull request by at-wat**

### CODE REVIEW

**Comment by jfreymuth** [comment]
Sorry for taking so long.
In my opinion, setting source/sink volumes is not something most programs should do, since it affects other applications running on the same system. Most users probably have a single volume control application and generally don't want other programs to change those settings.
I want to keep the API of the `pulse` package as simple as possible, and therefore not include functionality that is easy to misuse. (this is also why i removed direct access to the AdjustLatency flag, I don't expect users to understand exactly how to use it)
Instead I would like to make it easier to use the `proto` package directly, so users who need advanced functionality can use the "expert" package.

Let me know what you think, or if you have a specific use case for setting volumes that you would like the package to cover.

**Comment by at-wat** [comment]
@jfreymuth Thank you for your opinion!
I'm going to use the volume control feature in an agent working on an embedded system that is controlled from a cloud system.
There are other processes input/output audio, and I would like to control the master volume of the whole system.

So, I would like to suggest the following changes, if volume control should be by user program instead of by `pulse` package:
- add a getter to get underlying `proto.Client` from `pulse.Client`
  - otherwise, the user should create two connections to the pulse server to use both `pulse` and `proto` package, and in most case the user will copy whole `pulse.NewClient` function to the user code.
- add getters to get `Index` from `pulse.Source` and `pulse.Sink`

**Comment by jfreymuth** [comment]
I've added the (*Client).RawRequest() method to send arbitrary requests.
Also note that you added empty reply types to `proto`, this is not necessary, simply pass `nil` as reply.

**Comment by at-wat** [comment]
Thanks.
I tried to use `RawRequest()` to implement the same feature by
```go
// var s *pulse.Source = ...
c.RawRequest(&proto.SetSourceVolume{
  SourceName:     s.ID(),
  ChannelVolumes: cvol,
}
```
but specifying device by `SourceName` seems not working. (`pulseaudio: invalid argument` is returned.)
Using `SourceIndex` works as expected.

So, I think `Source/SinkIndex` getter of `pulse.Source/Sink` is needed.
Or, do I miss something?

**Comment by jfreymuth** [comment]
You need to set `SourceIndex` to `proto.Undefined` (-1) if you use a source name.

That means the getters are actually not needed, but I'll leave them in now.

**Comment by at-wat** [comment]
> You need to `set SourceIndex` to `proto.Undefined` (-1) if you use a source name.

Thank you. It worked.

**Pull request closed without merging**
