### PR TITLE
Add Volume and SetVolume to playback

### PR DESCRIPTION
**Pull request by aykevl**
This allows setting and getting the volume from an application that uses this library. It was already possible using raw requests, but this makes it a lot easier.

I might add volume notifications in the future (so that the user of the package can be notified when the application volume is changed by another program), but that's a bit more difficult to implement.

### CODE REVIEW

**Comment by jfreymuth** [comment]
I'd rather not add this, applications should (almost?) never change their own volume this way; keep in mind that this will override any settings made in a volume control application.

My goal for the `pulse` package is to make it easy to use and hard to misuse, so a feature that should only be used by utilities like a system volume control don't belong there.

I'm fine with the changes to the `proto` package though.

**Comment by aykevl** [comment]
Most media applications include a volume slider. YouTube has it, VLC has it, Elisa (KDE music player) has it, do you think that's a bad pattern? I don't know of an application that _doesn't_ have built-in volume control. Note that this PR is only for the application volume, it does not change global volume (which I agree should only ever be done by a volume control application integrated in the desktop).

Personally I basically never change application volume from system volume control. When I want different applications to have a different volume, I use the slider in the application itself because that's the most sensible place to do it.

**Comment by jfreymuth** [comment]
> Most media applications include a volume slider

I was going to say: "Yes, but none of these applications change the volume through PulseAudio" but after some testing it turns out VLC actually does -.-

The PulseAudio documentation "strongly recommends" not setting a volume when [*creating* a playback stream](https://freedesktop.org/software/pulseaudio/doxygen/stream_8h.html#ab9544f6677af133fbe81bf8a21eb489c), but I couldn't find anything else (other than the fact that the equivalent of the method you're adding ([`pa_context_set_sink_input_volume`](https://freedesktop.org/software/pulseaudio/doxygen/introspect_8h.html#a825ccd9e00765c0d397e2341086586ff)) is part of an API that seems intended for system volume mixers (["Sometimes it is necessary to query and modify global settings in the server. For this, PulseAudio has the introspection API"](https://freedesktop.org/software/pulseaudio/doxygen/introspect.html))

My opinion is still that applications should do volume sliders internally (by multiplying the samples before sending them to PulseAudio), mainly because most applications need some kind of client-side mixer anyway (even a simple media player might want a short fade-out when pausing; just cutting off the stream can cause a pop) so letting PulseAudio handle volume seems like a hack/shortcut that needs to be addressed when the application becomes more polished.

**Comment by aykevl** [comment]
I did some more testing. The following applications control the PA sink input volume directly:

- Firefox (playing a video in YouTube)
- Dragon Player
- VLC
- Rhythmbox
- Totem
- Showtime (installed from Flathub)

The following do not:

- Chromium
- Elisa (through ALSA)
- MPV
- Deadbeef (through ALSA)
- Audacity (through ALSA)

So it's pretty common (though far from universal) for applications to control volume directly through PulseAudio. And many of those that don't play their audio through ALSA (perhaps volume control is not universally supported on ALSA?)

I couldn't find anything definitive in the PulseAudio docs, though I did find [this part](https://freedesktop.org/software/pulseaudio/doxygen/volume.html) (emphasis mine):

> There is no single well-defined meaning attached to the 100% volume for a sink input. In fact, it depends on the server configuration. With flat volumes enabled, it means the maximum volume that the sound hardware is capable of, which is usually so high that you absolutely must not set sink input volume to 100% unless the the user explicitly requests that (*note that usually you shouldn't set the volume anyway if the user doesn't explicitly request it, instead, let PulseAudio decide the volume for the sink input*). With flat volumes disabled the sink input volume is relative to the sink volume, so 100% sink input volume means that the sink input is played at the current sink volume level. In this case 100% is often a good default volume for a sink input, although you still should let PulseAudio decide the default volume. It is possible to figure out whether flat volume mode is in effect for a given sink by calling [pa_context_get_sink_info_by_name()](https://freedesktop.org/software/pulseaudio/doxygen/introspect_8h.html#a446ffde2b8adea89940adcba40be319c).

Note the "if the user doesn't explicitly request it", using a volume slider seems pretty explicit to me.

**Comment by jfreymuth** [comment]
Ok, could you add something to the godoc comment? Maybe this quote from the PA docs: "It is strongly recommended that all volume changes are done as a direct result of user input" and that the initial setting should be queried, because PA may save/restore volume settings.

(Also "If an application changes any volume, it should also listen to changes of the same volume originating from outside the application (e.g., from the system mixer application) and update its user interface accordingly", but I'm fine with adding the subscription later)

**Comment by aykevl** [comment]
Thanks! I have updated the PR to fix these issues. The godoc comment is now pretty long, and explains how this API is supposed to be used.

And yes, I intend to add an API for listening to volume changes later. But it is a bit bigger and more complicated so I did the smaller PR first.

**Comment by aykevl** [comment]
Also fixed `ChannelVolumes.Avg` to match `pa_cvolume_avg` and use uint64 to avoid overflow.

**Pull request merged**
